# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/114/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/114/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/omer/CLionProjects/blockchain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/omer/CLionProjects/blockchain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/114/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/omer/CLionProjects/blockchain/CMakeFiles /home/omer/CLionProjects/blockchain/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/omer/CLionProjects/blockchain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blockchain

# Build rule for target.
blockchain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blockchain
.PHONY : blockchain

# fast build rule for target.
blockchain/fast:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/build
.PHONY : blockchain/fast

block.o: block.cpp.o

.PHONY : block.o

# target to build an object file
block.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/block.cpp.o
.PHONY : block.cpp.o

block.i: block.cpp.i

.PHONY : block.i

# target to preprocess a source file
block.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/block.cpp.i
.PHONY : block.cpp.i

block.s: block.cpp.s

.PHONY : block.s

# target to generate assembly for a file
block.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/block.cpp.s
.PHONY : block.cpp.s

blockchain.o: blockchain.cpp.o

.PHONY : blockchain.o

# target to build an object file
blockchain.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/blockchain.cpp.o
.PHONY : blockchain.cpp.o

blockchain.i: blockchain.cpp.i

.PHONY : blockchain.i

# target to preprocess a source file
blockchain.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/blockchain.cpp.i
.PHONY : blockchain.cpp.i

blockchain.s: blockchain.cpp.s

.PHONY : blockchain.s

# target to generate assembly for a file
blockchain.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/blockchain.cpp.s
.PHONY : blockchain.cpp.s

hash.o: hash.cpp.o

.PHONY : hash.o

# target to build an object file
hash.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/hash.cpp.o
.PHONY : hash.cpp.o

hash.i: hash.cpp.i

.PHONY : hash.i

# target to preprocess a source file
hash.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/hash.cpp.i
.PHONY : hash.cpp.i

hash.s: hash.cpp.s

.PHONY : hash.s

# target to generate assembly for a file
hash.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/hash.cpp.s
.PHONY : hash.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/main.cpp.s
.PHONY : main.cpp.s

miner.o: miner.cpp.o

.PHONY : miner.o

# target to build an object file
miner.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/miner.cpp.o
.PHONY : miner.cpp.o

miner.i: miner.cpp.i

.PHONY : miner.i

# target to preprocess a source file
miner.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/miner.cpp.i
.PHONY : miner.cpp.i

miner.s: miner.cpp.s

.PHONY : miner.s

# target to generate assembly for a file
miner.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/miner.cpp.s
.PHONY : miner.cpp.s

transaction.o: transaction.cpp.o

.PHONY : transaction.o

# target to build an object file
transaction.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/transaction.cpp.o
.PHONY : transaction.cpp.o

transaction.i: transaction.cpp.i

.PHONY : transaction.i

# target to preprocess a source file
transaction.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/transaction.cpp.i
.PHONY : transaction.cpp.i

transaction.s: transaction.cpp.s

.PHONY : transaction.s

# target to generate assembly for a file
transaction.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/transaction.cpp.s
.PHONY : transaction.cpp.s

user.o: user.cpp.o

.PHONY : user.o

# target to build an object file
user.cpp.o:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/user.cpp.o
.PHONY : user.cpp.o

user.i: user.cpp.i

.PHONY : user.i

# target to preprocess a source file
user.cpp.i:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/user.cpp.i
.PHONY : user.cpp.i

user.s: user.cpp.s

.PHONY : user.s

# target to generate assembly for a file
user.cpp.s:
	$(MAKE) -f CMakeFiles/blockchain.dir/build.make CMakeFiles/blockchain.dir/user.cpp.s
.PHONY : user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... blockchain"
	@echo "... block.o"
	@echo "... block.i"
	@echo "... block.s"
	@echo "... blockchain.o"
	@echo "... blockchain.i"
	@echo "... blockchain.s"
	@echo "... hash.o"
	@echo "... hash.i"
	@echo "... hash.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... miner.o"
	@echo "... miner.i"
	@echo "... miner.s"
	@echo "... transaction.o"
	@echo "... transaction.i"
	@echo "... transaction.s"
	@echo "... user.o"
	@echo "... user.i"
	@echo "... user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

